### ISSUE TITLE
Error MD5 response.

### ISSUE THREAD

**Issue by dengbo22** [iseekwonderful/DrCOM-Scut#1]
因为自己使用的是Python3.5版本，所以源代码不可以使用，scary当前有python3的测试版本scary-python3，想请问大神能不能改出来一个python3的版本？
另外，自己在改python3版本的时候，在发送MD5_Response的时候使用Wireshark抓包，获取到报文为：
Code: Request(1) , Type: Notification (2) , Notification:  userid error3.个人在想是不是在EAP验证的最后一环出了问题，自己在用ID + password + MD5_request重新进行MD5计算的时候（MD5_request使用客户端正确登录的wireshark抓包获得的EAP-MD5 Value内容），发现计算的MD5和客户端实际返回的MD5不一致，求大神解答.
环境：Windows 10. Python3.5.  PyCharm.

**Comment by iseekwonderful** [comment]
你是南校还是北校的？
我这边是没有问题， 你可以把代码贴上来看下吗？

**Comment by ghost** [comment]
请问你是南校还是北校呢？

**Comment by iseekwonderful** [comment]
南校

**Comment by iseekwonderful** [comment]
有木有大神写个openwrt的啊？

**Comment by ghost** [comment]
认证后能稳定不断网吗？

**Comment by iseekwonderful** [comment]
并不能T T，但是会自动重连

**Comment by dengbo22** [comment]
我后来抓包的时候发现他有不断的发过来认证报文，然后客户端的动作的根据那个ID返回内容，所以可能你需要在send_id_response里面根据发来的ID返回不同的内容。另外好像Windows下这个确实不能用……MD5校验错误，难道加密方式不一样？

**Comment by iseekwonderful** [comment]
没在windows下试过
华工路由器群的大神已经开发好openwrt的版本了
等发布吧～
